version: '3.8'
services:
  nginx:
    image: library/nginx:1.19-alpine
    container_name: "charlie_nginx"
    ports:
      - 8384:80
    user: "0:0"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/html"
    links:
      - php
  php:
    image: "charlie_php"
    build: ./php
    user: "0:0"
    environment:
      - PUID=0
      - PGID=0
    container_name: "charlie_php"
    volumes:
      - "./app:/var/www/html"
